version: '3'
services:
  app:
    build: app
    environment:
      RAILS_ENV: development
    ports:
      - '3000:3000'
    volumes:
      - ./app:/var/app/takehome
  web:
    build:
      context: containers/nginx
    ports:
      - 80:80
    depends_on:
      - app
